# Generated by Django 5.2.17 on 2026-08-29 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipos_reporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('en_progreso', 'En progreso')], default='en_progreso', max_length=20)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_creados', to=settings.AUTH_USER_MODEL)),
                ('definicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='tipos_reporte.definiciondetipo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='tipos_reporte.tipodereporte')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
            },
        ),
        migrations.CreateModel(
            name='ValorDeReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_de_campo', models.CharField(max_length=200)),
                ('valor', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valores_escritos', to=settings.AUTH_USER_MODEL)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='reportes.reporte')),
            ],
            options={
                'verbose_name': 'Valor de reporte',
                'verbose_name_plural': 'Valores de reporte',
                'constraints': [models.UniqueConstraint(fields=('reporte', 'identificador_de_campo'), name='valor_unico_por_reporte_y_campo')],
            },
        ),
    ]
