# Generated by Django 5.2.17 on 2026-08-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='estado',
            field=models.CharField(choices=[('en_progreso', 'En progreso'), ('terminado', 'Terminado')], default='en_progreso', max_length=20),
        ),
    ]
