# Generated by Django 5.2.17 on 2026-08-29 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_estado_terminado'),
        ('tipos_reporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Generacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('definicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generaciones', to='tipos_reporte.definiciondetipo')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generaciones', to='reportes.reporte')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generación',
                'verbose_name_plural': 'Generaciones',
            },
        ),
        migrations.CreateModel(
            name='VistoBueno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visto_bueno', to='reportes.reporte')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vistos_buenos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visto bueno',
                'verbose_name_plural': 'Vistos buenos',
            },
        ),
    ]
