# Generated by Django 5.2.17 on 2026-08-29 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_vistobueno_generacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioDeValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_de_campo', models.CharField(max_length=200)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_de_valor', to=settings.AUTH_USER_MODEL)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='reportes.reporte')),
            ],
            options={
                'verbose_name': 'Cambio de valor',
                'verbose_name_plural': 'Cambios de valor',
            },
        ),
        migrations.CreateModel(
            name='ParticipacionEnReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_invitacion', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='reportes.reporte')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participación en reporte',
                'verbose_name_plural': 'Participaciones en reporte',
                'constraints': [models.UniqueConstraint(fields=('reporte', 'usuario'), name='participacion_unica_por_reporte_y_usuario')],
            },
        ),
    ]
