# Generated by Django 5.2.17 on 2026-08-30 17:20
#
# Generated for change `adjuntos` (backlog #11, design D1). Single additive
# `CreateModel` — no existing table is altered. Rollback:
# `manage.py migrate reportes 0005` (tasks.md 1.4); the model has no callers
# yet in this PR (tasks.md Suggested Work Units, Unit 1).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_id_local_numero_registro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion_id', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('croquis', 'Croquis'), ('evidencia', 'Evidencia')], max_length=20)),
                ('archivo', models.FileField(max_length=500, upload_to='reportes/adjuntos/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('formato_original', models.CharField(max_length=100)),
                ('tamano_bytes', models.PositiveIntegerField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjuntos_subidos', to=settings.AUTH_USER_MODEL)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='reportes.reporte')),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
                'ordering': ('fecha_subida', 'id'),
            },
        ),
    ]
