"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17, then edited
for environment-driven configuration (decision 3) and the custom Usuario
model (decision 1).

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loads variables from a local .env file into os.environ. This is a
# silent no-op when .env is absent (e.g. on a future deployment target
# that sets real environment variables directly), and it never overrides
# already-set environment variables.
load_dotenv(BASE_DIR / ".env")


def require_env(name):
    """Fail loudly at startup instead of silently defaulting."""
    try:
        return os.environ[name]
    except KeyError:
        raise ImproperlyConfigured(f"Missing required environment variable: {name}")


def require_bool_env(name):
    """require_env() for a strict boolean. Rejects 'true', '1', 'yes'."""
    value = require_env(name)
    if value not in ("True", "False"):
        raise ImproperlyConfigured(
            f"{name} must be exactly 'True' or 'False', got {value!r}"
        )
    return value == "True"


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = require_env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

ALLOWED_HOSTS = [h.strip() for h in require_env("DJANGO_ALLOWED_HOSTS").split(",")]

CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if o.strip()
]

# Vercel terminates TLS at its edge and forwards the original scheme in this
# header, so request.is_secure() is False without it (design decision 4).
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Is this deployment served exclusively over HTTPS? A deployment fact the
# app is told, never infers. No value is safe in both places, so it is
# fail-loud (design decision 11).
HTTPS_ONLY = require_bool_env("DJANGO_HTTPS_ONLY")

SESSION_COOKIE_SECURE = HTTPS_ONLY
CSRF_COOKIE_SECURE = HTTPS_ONLY
SECURE_SSL_REDIRECT = HTTPS_ONLY

# One hour, deliberately short: browsers cache HSTS, so it cannot be
# withdrawn from the server side (design decision 11).
SECURE_HSTS_SECONDS = 3600 if HTTPS_ONLY else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = HTTPS_ONLY
SECURE_HSTS_PRELOAD = False

# security.W021 asks for SECURE_HSTS_PRELOAD. The browser preload list is
# keyed on registrable domains; vercel.app is a public suffix this project
# does not own, so the directive could never take effect. Silenced
# deliberately, with a reason - not ignored (design decision 11).
SILENCED_SYSTEM_CHECKS = ["security.W021"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.parse(require_env("DATABASE_URL")),
}

# Distinct test database name so concurrent developers/CI runners don't
# collide on the same Neon dev branch (decision 6).
DATABASES["default"]["TEST"] = {
    "NAME": os.environ.get("TEST_DB_NAME", "test_reportes_dev"),
}

# Connection-per-request: Neon's pooler absorbs the churn (design decision 6).
DATABASES["default"]["CONN_MAX_AGE"] = 0


# Custom user model (decision 1). Must be set before the first migration.
AUTH_USER_MODEL = "usuarios.Usuario"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Vercel doesn't serve /static/ from outputDirectory the way it does for
# static-site frameworks -- confirmed empirically (127 files collected but
# every request still hit the WSGI function). WhiteNoise serves them from
# inside the function itself instead (design Decision 5, superseded).
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Auth / session settings (decision 4)

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "inicio"
LOGOUT_REDIRECT_URL = "login"
SESSION_COOKIE_AGE = 604800  # 7 days
