# Generated by Django 5.2.17 on 2026-08-28 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefinicionDeTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_yaml', models.FileField(upload_to='tipos_reporte/definiciones/')),
                ('yaml_fuente', models.TextField()),
                ('estructura', models.JSONField()),
                ('version', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('historica', 'Histórica')], default='borrador', max_length=20)),
                ('activada_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Definición de tipo',
                'verbose_name_plural': 'Definiciones de tipo',
            },
        ),
        migrations.CreateModel(
            name='TipoDeReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('version_formato', models.CharField(blank=True, default='', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tipos_reporte/logos/')),
                ('plantilla', models.FileField(upload_to='tipos_reporte/plantillas/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('definicion_activa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipos_donde_es_activa', to='tipos_reporte.definiciondetipo')),
            ],
            options={
                'verbose_name': 'Tipo de reporte',
                'verbose_name_plural': 'Tipos de reporte',
            },
        ),
        migrations.AddField(
            model_name='definiciondetipo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definiciones', to='tipos_reporte.tipodereporte'),
        ),
        migrations.AddConstraint(
            model_name='definiciondetipo',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activa')), fields=('tipo',), name='definicion_una_activa_por_tipo'),
        ),
        migrations.AddConstraint(
            model_name='definiciondetipo',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'borrador')), fields=('tipo',), name='definicion_un_borrador_por_tipo'),
        ),
        migrations.AddConstraint(
            model_name='definiciondetipo',
            constraint=models.UniqueConstraint(condition=models.Q(('version__isnull', False)), fields=('tipo', 'version'), name='definicion_version_unica_por_tipo'),
        ),
        migrations.AddConstraint(
            model_name='definiciondetipo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'borrador'), ('version__isnull', True), ('activada_en__isnull', True)), models.Q(models.Q(('estado', 'borrador'), _negated=True), ('version__isnull', False), ('activada_en__isnull', False)), _connector='OR'), name='definicion_estado_implica_version'),
        ),
    ]
