# Generated by Django 5.2.17 on 2026-08-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipos_reporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definiciondetipo',
            name='archivo_yaml',
            field=models.FileField(max_length=500, upload_to='tipos_reporte/definiciones/'),
        ),
        migrations.AlterField(
            model_name='tipodereporte',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='tipos_reporte/logos/'),
        ),
        migrations.AlterField(
            model_name='tipodereporte',
            name='plantilla',
            field=models.FileField(max_length=500, upload_to='tipos_reporte/plantillas/'),
        ),
    ]
